FROM continuumio/miniconda

MAINTAINER ben.koziol@gmail.com

RUN conda create -n test-python-2.7 -c nesii -c conda-forge esmpy nose python=2.7

RUN conda create -n test-ocgis-2.7 -c nesii/channel/dev-ocgis -c conda-forge ocgis nose python=2.7
RUN conda create -n test-ocgis-3.5 -c nesii/channel/dev-ocgis -c conda-forge ocgis nose python=3.5
RUN conda create -n test-ocgis-3.6 -c nesii/channel/dev-ocgis -c conda-forge ocgis nose python=3.6
