FROM continuumio/miniconda

MAINTAINER ben.koziol@gmail.com

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get -y install build-essential
RUN apt-get -y install gfortran
RUN apt-get -y install m4
RUN apt-get clean

RUN conda install conda-build
RUN conda install anaconda-client
